=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/ccu_order_active.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "array",
    "null"
  ],
  "items": {
    "type": "object",
    "properties": {
      "orderType": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "timestamp": {
        "type": "string"
      },
      "orderId": {
        "type": "string"
      },
      "productionSteps": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "source": {
              "type": "string"
            },
            "target": {
              "type": "string"
            },
            "startedAt": {
              "type": "string"
            },
            "stoppedAt": {
              "type": "string"
            },
            "dependentActionId": {
              "type": "string"
            },
            "command": {
              "type": "string"
            },
            "moduleType": {
              "type": "string"
            },
            "serialNumber": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "state",
            "type"
          ]
        }
      },
      "receivedAt": {
        "type": "string"
      },
      "state": {
        "type": "string"
      },
      "workpieceId": {
        "type": "string"
      },
      "startedAt": {
        "type": "string"
      }
    },
    "required": [
      "orderId",
      "orderType",
      "productionSteps",
      "receivedAt",
      "startedAt",
      "state",
      "timestamp",
      "type"
    ]
  },
  "title": "Ccu_Order_Active Schema",
  "description": "Granular schema for ccu_order_active topics from 132 examples",
  "category": "ccu",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/ccu_order_active__000208.json
[
  {
    "orderType": "PRODUCTION",
    "type": "RED",
    "timestamp": "2025-10-01T11:18:12.977Z",
    "orderId": "aa74c367-dfc6-4c3b-b669-af293ea717f1",
    "productionSteps": [
      {
        "id": "9d8345a6-c3ca-4805-a043-e9c6786f93ea",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "START",
        "target": "HBW",
        "startedAt": "2025-10-01T11:18:13.046Z",
        "stoppedAt": "2025-10-01T11:18:15.119Z"
      },
      {
        "id": "40d61b13-4d66-48ad-83bc-525b61f66925",
        "type": "MANUFACTURE",
        "dependentActionId": "9d8345a6-c3ca-4805-a043-e9c6786f93ea",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "HBW",
        "startedAt": "2025-10-01T11:18:15.123Z",
        "serialNumber": "SVR3QA0022",
        "stoppedAt": "2025-10-01T11:19:08.792Z"
      },
      {
        "id": "6ed86563-5fba-454e-a737-b866d8f30e05",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "HBW",
        "target": "MILL",
        "dependentActionId": "40d61b13-4d66-48ad-83bc-525b61f66925",
        "startedAt": "2025-10-01T11:19:08.992Z",
        "stoppedAt": "2025-10-01T11:19:18.644Z"
      },
      {
        "id": "51d9af47-9e83-41d3-991c-23ea1beab81c",
        "type": "MANUFACTURE",
        "dependentActionId": "6ed86563-5fba-454e-a737-b866d8f30e05",
        "state": "FINISHED",
        "command": "PICK",
        "moduleType": "MILL",
        "startedAt": "2025-10-01T11:19:18.650Z",
        "serialNumber": "SVR3QA2098",
        "stoppedAt": "2025-10-01T11:19:28.266Z"
      },
      {
        "id": "d1e15ed3-584f-4e7d-8eb9-6160a4f23a74",
        "type": "MANUFACTURE",
        "dependentActionId": "51d9af47-9e83-41d3-991c-23ea1beab81c",
        "state": "FINISHED",
        "command": "MILL",
        "moduleType": "MILL",
        "startedAt": "2025-10-01T11:19:28.271Z",
        "serialNumber": "SVR3QA2098",
        "stoppedAt": "2025-10-01T11:19:38.216Z"
      },
      {
        "id": "1d6b6de5-68e5-4387-914c-9d6ffe4f29ca",
        "type": "MANUFACTURE",
        "dependentActionId": "d1e15ed3-584f-4e7d-8eb9-6160a4f23a74",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "MILL",
        "startedAt": "2025-10-01T11:19:38.230Z",
        "serialNumber": "SVR3QA2098",
        "stoppedAt": "2025-10-01T11:19:47.397Z"
      },
      {
        "id": "3525b196-dd80-4a3b-8684-7f4da35eaf36",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "MILL",
        "target": "AIQS",
        "dependentActionId": "1d6b6de5-68e5-4387-914c-9d6ffe4f29ca",
        "startedAt": "2025-10-01T11:19:47.582Z",
        "stoppedAt": "2025-10-01T11:20:02.900Z"
      },
      {
        "id": "d572f2ce-0cfd-42ff-8471-c1e0d7ad0b55",
        "type": "MANUFACTURE",
        "dependentActionId": "3525b196-dd80-4a3b-8684-7f4da35eaf36",
        "state": "FINISHED",
        "command": "PICK",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T11:20:02.903Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T11:20:11.150Z"
      },
      {
        "id": "546ff327-0133-4255-b3c1-c5295196cea9",
        "type": "MANUFACTURE",
        "dependentActionId": "d572f2ce-0cfd-42ff-8471-c1e0d7ad0b55",
        "state": "FINISHED",
        "command": "CHECK_QUALITY",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T11:20:11.153Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T11:20:19.102Z"
      },
      {
        "id": "1a252db6-3cad-4f82-a0a8-2b040461370b",
        "type": "MANUFACTURE",
        "dependentActionId": "546ff327-0133-4255-b3c1-c5295196cea9",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T11:20:19.117Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T11:20:28.238Z"
      },
      {
        "id": "171d6d8d-c150-4f61-b272-734baf699ce7",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "AIQS",
        "target": "DPS",
        "dependentActionId": "1a252db6-3cad-4f82-a0a8-2b040461370b",
        "startedAt": "2025-10-01T11:20:28.423Z",
        "stoppedAt": "2025-10-01T11:20:37.855Z"
      },
      {
        "id": "1021192a-0dc9-4ee1-9251-48951415354e",
        "type": "MANUFACTURE",
        "dependentActionId": "171d6d8d-c150-4f61-b272-734baf699ce7",
        "state": "IN_PROGRESS",
        "command": "PICK",
        "moduleType": "DPS",
        "startedAt": "2025-10-01T11:20:37.860Z",
        "serialNumber": "SVR4H73275"
      }
    ],
    "receivedAt": "2025-10-01T11:18:13.027Z",
    "state": "IN_PROGRESS",
    "workpieceId": "040a8dca341291",
    "startedAt": "2025-10-01T11:18:13.028Z"
  }
]
