=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/ccu_order_active.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "array",
    "null"
  ],
  "items": {
    "type": "object",
    "properties": {
      "orderType": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "timestamp": {
        "type": "string"
      },
      "orderId": {
        "type": "string"
      },
      "productionSteps": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "source": {
              "type": "string"
            },
            "target": {
              "type": "string"
            },
            "startedAt": {
              "type": "string"
            },
            "stoppedAt": {
              "type": "string"
            },
            "dependentActionId": {
              "type": "string"
            },
            "command": {
              "type": "string"
            },
            "moduleType": {
              "type": "string"
            },
            "serialNumber": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "state",
            "type"
          ]
        }
      },
      "receivedAt": {
        "type": "string"
      },
      "state": {
        "type": "string"
      },
      "workpieceId": {
        "type": "string"
      },
      "startedAt": {
        "type": "string"
      }
    },
    "required": [
      "orderId",
      "orderType",
      "productionSteps",
      "receivedAt",
      "startedAt",
      "state",
      "timestamp",
      "type"
    ]
  },
  "title": "Ccu_Order_Active Schema",
  "description": "Granular schema for ccu_order_active topics from 132 examples",
  "category": "ccu",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/ccu_order_active__000282.json
[
  {
    "orderType": "PRODUCTION",
    "type": "RED",
    "timestamp": "2025-10-01T11:36:10.096Z",
    "orderId": "06dbdb8a-311e-4cf0-b76d-1366317cbccc",
    "productionSteps": [
      {
        "id": "f18b9cbe-cfa4-414c-bfa5-547af27ef169",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "START",
        "target": "HBW",
        "startedAt": "2025-10-01T11:38:08.965Z",
        "stoppedAt": "2025-10-01T11:38:20.722Z"
      },
      {
        "id": "15ff7822-b9c8-46cd-9935-649ea2be427b",
        "type": "MANUFACTURE",
        "dependentActionId": "f18b9cbe-cfa4-414c-bfa5-547af27ef169",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "HBW",
        "startedAt": "2025-10-01T11:38:20.727Z",
        "serialNumber": "SVR3QA0022",
        "stoppedAt": "2025-10-01T11:39:07.226Z"
      },
      {
        "id": "d3889a3d-9590-4d6f-a2ea-9961a5ac990c",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "HBW",
        "target": "MILL",
        "dependentActionId": "15ff7822-b9c8-46cd-9935-649ea2be427b",
        "startedAt": "2025-10-01T11:39:07.398Z",
        "stoppedAt": "2025-10-01T11:39:16.786Z"
      },
      {
        "id": "52b705c8-e7b9-4ab1-9571-7c9808ecca23",
        "type": "MANUFACTURE",
        "dependentActionId": "d3889a3d-9590-4d6f-a2ea-9961a5ac990c",
        "state": "FINISHED",
        "command": "PICK",
        "moduleType": "MILL",
        "startedAt": "2025-10-01T11:39:16.791Z",
        "serialNumber": "SVR3QA2098",
        "stoppedAt": "2025-10-01T11:39:26.680Z"
      },
      {
        "id": "0ce88144-07b3-4129-b707-cba1e6178c6e",
        "type": "MANUFACTURE",
        "dependentActionId": "52b705c8-e7b9-4ab1-9571-7c9808ecca23",
        "state": "FINISHED",
        "command": "MILL",
        "moduleType": "MILL",
        "startedAt": "2025-10-01T11:39:26.685Z",
        "serialNumber": "SVR3QA2098",
        "stoppedAt": "2025-10-01T11:39:35.831Z"
      },
      {
        "id": "9f7e1a84-c552-4410-b9f1-eca51854f5e9",
        "type": "MANUFACTURE",
        "dependentActionId": "0ce88144-07b3-4129-b707-cba1e6178c6e",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "MILL",
        "startedAt": "2025-10-01T11:39:35.846Z",
        "serialNumber": "SVR3QA2098",
        "stoppedAt": "2025-10-01T11:39:45.783Z"
      },
      {
        "id": "6959a2c7-ecbb-40de-8884-3ca03484ccc6",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "MILL",
        "target": "AIQS",
        "dependentActionId": "9f7e1a84-c552-4410-b9f1-eca51854f5e9",
        "startedAt": "2025-10-01T11:39:45.927Z",
        "stoppedAt": "2025-10-01T11:39:59.089Z"
      },
      {
        "id": "3b2f383f-5615-4c8b-a2bd-842ccb5e738b",
        "type": "MANUFACTURE",
        "dependentActionId": "6959a2c7-ecbb-40de-8884-3ca03484ccc6",
        "state": "FINISHED",
        "command": "PICK",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T11:39:59.094Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T11:40:07.052Z"
      },
      {
        "id": "f86efb7f-1d8f-4e39-92f5-e3e46b72ece6",
        "type": "MANUFACTURE",
        "dependentActionId": "3b2f383f-5615-4c8b-a2bd-842ccb5e738b",
        "state": "FINISHED",
        "command": "CHECK_QUALITY",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T11:40:07.055Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T11:40:16.027Z"
      },
      {
        "id": "41f3bac8-b302-4bfe-82a3-3be9c7be203b",
        "type": "MANUFACTURE",
        "dependentActionId": "f86efb7f-1d8f-4e39-92f5-e3e46b72ece6",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T11:40:16.036Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T11:40:24.915Z"
      },
      {
        "id": "b3450351-fe35-4f98-a9be-ad9ff28dc1fb",
        "type": "NAVIGATION",
        "state": "ENQUEUED",
        "source": "AIQS",
        "target": "DPS",
        "dependentActionId": "41f3bac8-b302-4bfe-82a3-3be9c7be203b"
      },
      {
        "id": "d7f1dff7-526a-41da-a1c1-a5aab8f26f47",
        "type": "MANUFACTURE",
        "dependentActionId": "b3450351-fe35-4f98-a9be-ad9ff28dc1fb",
        "state": "ENQUEUED",
        "command": "PICK",
        "moduleType": "DPS"
      }
    ],
    "receivedAt": "2025-10-01T11:38:08.924Z",
    "state": "IN_PROGRESS",
    "workpieceId": "040a8dca341291",
    "startedAt": "2025-10-01T11:38:08.924Z"
  }
]

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/ccu_order_active__000069.json
[
  {
    "orderType": "STORAGE",
    "type": "RED",
    "timestamp": "2025-10-01T09:58:06.779Z",
    "orderId": "50fdbb01-1cf6-45c1-a24b-7171f9cab3e2",
    "productionSteps": [
      {
        "id": "320d2896-8d0e-44e2-8122-d9ba45384fc4",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "START",
        "target": "DPS",
        "startedAt": "2025-10-01T09:58:06.948Z",
        "stoppedAt": "2025-10-01T09:58:17.494Z"
      },
      {
        "id": "98054187-eef0-4dab-8592-8985e3021230",
        "type": "MANUFACTURE",
        "dependentActionId": "320d2896-8d0e-44e2-8122-d9ba45384fc4",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "DPS",
        "startedAt": "2025-10-01T09:58:17.497Z",
        "serialNumber": "SVR4H73275",
        "stoppedAt": "2025-10-01T09:58:31.894Z"
      },
      {
        "id": "64064863-72a5-4ba2-8eb1-e8eef7569b5e",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "DPS",
        "target": "HBW",
        "dependentActionId": "98054187-eef0-4dab-8592-8985e3021230",
        "startedAt": "2025-10-01T09:58:32.053Z",
        "stoppedAt": "2025-10-01T09:58:42.547Z"
      },
      {
        "id": "f9a58606-e76a-4cdd-9bc0-8c089fb5537c",
        "type": "MANUFACTURE",
        "dependentActionId": "64064863-72a5-4ba2-8eb1-e8eef7569b5e",
        "state": "IN_PROGRESS",
        "command": "PICK",
        "moduleType": "HBW",
        "startedAt": "2025-10-01T09:58:42.552Z",
        "serialNumber": "SVR3QA0022"
      }
    ],
    "receivedAt": "2025-10-01T09:58:06.884Z",
    "state": "IN_PROGRESS",
    "workpieceId": "040a8dca341291",
    "startedAt": "2025-10-01T09:58:06.884Z"
  }
]

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/ccu_order_active__000050.json
[
  {
    "orderType": "STORAGE",
    "type": "WHITE",
    "timestamp": "2025-10-01T09:53:51.969Z",
    "orderId": "5e0cc980-785a-44fc-a690-3e3ac2eaabd3",
    "productionSteps": [
      {
        "id": "ce016d78-4598-4752-bbf6-f1cc69d1f311",
        "type": "NAVIGATION",
        "state": "IN_PROGRESS",
        "source": "START",
        "target": "DPS",
        "startedAt": "2025-10-01T09:53:52.055Z"
      },
      {
        "id": "04cad677-4488-4db7-8e8c-b7f770c41dd5",
        "type": "MANUFACTURE",
        "dependentActionId": "ce016d78-4598-4752-bbf6-f1cc69d1f311",
        "state": "ENQUEUED",
        "command": "DROP",
        "moduleType": "DPS"
      },
      {
        "id": "5eb0ae0b-3f88-4b40-b7c7-f82f79b7484a",
        "type": "NAVIGATION",
        "state": "ENQUEUED",
        "source": "DPS",
        "target": "HBW",
        "dependentActionId": "04cad677-4488-4db7-8e8c-b7f770c41dd5"
      },
      {
        "id": "25a0f241-c8b1-4c67-bc1a-24e45107b08d",
        "type": "MANUFACTURE",
        "dependentActionId": "5eb0ae0b-3f88-4b40-b7c7-f82f79b7484a",
        "state": "ENQUEUED",
        "command": "PICK",
        "moduleType": "HBW"
      }
    ],
    "receivedAt": "2025-10-01T09:53:52.031Z",
    "state": "IN_PROGRESS",
    "workpieceId": "047b8bca341291",
    "startedAt": "2025-10-01T09:53:52.032Z"
  }
]

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/ccu_order_active__000260.json
[
  {
    "orderType": "STORAGE",
    "type": "BLUE",
    "timestamp": "2025-10-01T10:06:20.280Z",
    "orderId": "8b54cc26-e37b-4428-887e-35da7fb574fd",
    "productionSteps": [
      {
        "id": "59ada0e9-8003-4d1a-bd32-130a7160e924",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "START",
        "target": "DPS",
        "startedAt": "2025-10-01T10:06:20.415Z",
        "stoppedAt": "2025-10-01T10:06:22.428Z"
      },
      {
        "id": "789b7014-836d-44d2-b17b-2d661222c96b",
        "type": "MANUFACTURE",
        "dependentActionId": "59ada0e9-8003-4d1a-bd32-130a7160e924",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "DPS",
        "startedAt": "2025-10-01T10:06:22.431Z",
        "serialNumber": "SVR4H73275",
        "stoppedAt": "2025-10-01T10:06:36.537Z"
      },
      {
        "id": "ecbe41ce-f742-4b96-9f32-672e92dff01e",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "DPS",
        "target": "HBW",
        "dependentActionId": "789b7014-836d-44d2-b17b-2d661222c96b",
        "startedAt": "2025-10-01T10:06:36.882Z",
        "stoppedAt": "2025-10-01T10:06:46.751Z"
      },
      {
        "id": "bce1f53c-065c-4dd9-ad87-e2ac6cbc265d",
        "type": "MANUFACTURE",
        "dependentActionId": "ecbe41ce-f742-4b96-9f32-672e92dff01e",
        "state": "IN_PROGRESS",
        "command": "PICK",
        "moduleType": "HBW",
        "startedAt": "2025-10-01T10:06:46.758Z",
        "serialNumber": "SVR3QA0022"
      }
    ],
    "receivedAt": "2025-10-01T10:06:20.387Z",
    "state": "IN_PROGRESS",
    "workpieceId": "047389ca341291",
    "startedAt": "2025-10-01T10:06:20.388Z"
  }
]

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/ccu_order_response__000141.json
{
  "orderType": "STORAGE",
  "type": "BLUE",
  "timestamp": "2025-10-01T09:36:23.886Z",
  "orderId": "5e75ef1f-6091-4ec0-b71c-4d54968593f9",
  "productionSteps": [
    {
      "id": "897998c8-a417-44b6-9e7d-3e0b21ceb9e7",
      "type": "NAVIGATION",
      "state": "IN_PROGRESS",
      "source": "START",
      "target": "DPS",
      "startedAt": "2025-10-01T09:36:24.023Z"
    },
    {
      "id": "469d2509-ce19-45cd-b5ba-29b845d2b8fe",
      "type": "MANUFACTURE",
      "dependentActionId": "897998c8-a417-44b6-9e7d-3e0b21ceb9e7",
      "state": "ENQUEUED",
      "command": "DROP",
      "moduleType": "DPS"
    },
    {
      "id": "338a3257-e684-4179-82d3-4ed7d68a315b",
      "type": "NAVIGATION",
      "state": "ENQUEUED",
      "source": "DPS",
      "target": "HBW",
      "dependentActionId": "469d2509-ce19-45cd-b5ba-29b845d2b8fe"
    },
    {
      "id": "90b73246-bd52-47e4-b602-ab2c984cdfaf",
      "type": "MANUFACTURE",
      "dependentActionId": "338a3257-e684-4179-82d3-4ed7d68a315b",
      "state": "ENQUEUED",
      "command": "PICK",
      "moduleType": "HBW"
    }
  ],
  "receivedAt": "2025-10-01T09:36:23.992Z",
  "state": "IN_PROGRESS",
  "workpieceId": "042c88ca341291",
  "startedAt": "2025-10-01T09:36:23.992Z"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/ccu_order_active__000422.json
[
  {
    "orderType": "PRODUCTION",
    "type": "WHITE",
    "timestamp": "2025-10-01T09:38:37.420Z",
    "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
    "productionSteps": [
      {
        "id": "045c08f2-dc8a-4bfc-923c-6aaacd60237a",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "START",
        "target": "HBW",
        "startedAt": "2025-10-01T09:38:37.531Z",
        "stoppedAt": "2025-10-01T09:38:39.575Z"
      },
      {
        "id": "7828b789-d790-4d49-97dd-d5c076975561",
        "type": "MANUFACTURE",
        "dependentActionId": "045c08f2-dc8a-4bfc-923c-6aaacd60237a",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "HBW",
        "startedAt": "2025-10-01T09:38:39.577Z",
        "serialNumber": "SVR3QA0022",
        "stoppedAt": "2025-10-01T09:39:20.402Z"
      },
      {
        "id": "80d11088-e361-4617-b04f-d946e900f313",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "HBW",
        "target": "DRILL",
        "dependentActionId": "7828b789-d790-4d49-97dd-d5c076975561",
        "startedAt": "2025-10-01T09:39:20.503Z",
        "stoppedAt": "2025-10-01T09:39:33.898Z"
      },
      {
        "id": "001a13d9-b0bf-4c74-9703-8c0ed6c18930",
        "type": "MANUFACTURE",
        "dependentActionId": "80d11088-e361-4617-b04f-d946e900f313",
        "state": "FINISHED",
        "command": "PICK",
        "moduleType": "DRILL",
        "startedAt": "2025-10-01T09:39:33.901Z",
        "serialNumber": "SVR4H76449",
        "stoppedAt": "2025-10-01T09:39:44.958Z"
      },
      {
        "id": "5106ad8a-34a4-4e12-adb4-83004e0c03fc",
        "type": "MANUFACTURE",
        "dependentActionId": "001a13d9-b0bf-4c74-9703-8c0ed6c18930",
        "state": "FINISHED",
        "command": "DRILL",
        "moduleType": "DRILL",
        "startedAt": "2025-10-01T09:39:44.960Z",
        "serialNumber": "SVR4H76449",
        "stoppedAt": "2025-10-01T09:39:53.910Z"
      },
      {
        "id": "5c85ed99-f941-4f51-82e6-faab236ff899",
        "type": "MANUFACTURE",
        "dependentActionId": "5106ad8a-34a4-4e12-adb4-83004e0c03fc",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "DRILL",
        "startedAt": "2025-10-01T09:39:53.922Z",
        "serialNumber": "SVR4H76449",
        "stoppedAt": "2025-10-01T09:40:04.865Z"
      },
      {
        "id": "06d04f01-df74-4fda-a77b-2718c9dd9947",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "DRILL",
        "target": "AIQS",
        "dependentActionId": "5c85ed99-f941-4f51-82e6-faab236ff899",
        "startedAt": "2025-10-01T09:40:05.014Z",
        "stoppedAt": "2025-10-01T09:40:23.100Z"
      },
      {
        "id": "71d1a4a5-b745-4bb1-a912-5ec45d1da862",
        "type": "MANUFACTURE",
        "dependentActionId": "06d04f01-df74-4fda-a77b-2718c9dd9947",
        "state": "FINISHED",
        "command": "PICK",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T09:40:23.106Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T09:40:31.386Z"
      },
      {
        "id": "de12ed6f-ee6c-4b41-9427-ed568ee4f793",
        "type": "MANUFACTURE",
        "dependentActionId": "71d1a4a5-b745-4bb1-a912-5ec45d1da862",
        "state": "FINISHED",
        "command": "CHECK_QUALITY",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T09:40:31.390Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T09:40:39.326Z"
      },
      {
        "id": "bb23112b-b2e3-4f88-aadf-1010c8a0cfa3",
        "type": "MANUFACTURE",
        "dependentActionId": "de12ed6f-ee6c-4b41-9427-ed568ee4f793",
        "state": "FINISHED",
        "command": "DROP",
        "moduleType": "AIQS",
        "startedAt": "2025-10-01T09:40:39.342Z",
        "serialNumber": "SVR4H76530",
        "stoppedAt": "2025-10-01T09:40:48.445Z"
      },
      {
        "id": "53eff382-aa9b-4b76-8223-b41761e93a35",
        "type": "NAVIGATION",
        "state": "FINISHED",
        "source": "AIQS",
        "target": "DPS",
        "dependentActionId": "bb23112b-b2e3-4f88-aadf-1010c8a0cfa3",
        "startedAt": "2025-10-01T09:40:48.618Z",
        "stoppedAt": "2025-10-01T09:40:57.960Z"
      },
      {
        "id": "63a451a9-f6d2-4008-869e-0e588469e1f2",
        "type": "MANUFACTURE",
        "dependentActionId": "53eff382-aa9b-4b76-8223-b41761e93a35",
        "state": "IN_PROGRESS",
        "command": "PICK",
        "moduleType": "DPS",
        "startedAt": "2025-10-01T09:40:57.967Z",
        "serialNumber": "SVR4H73275"
      }
    ],
    "receivedAt": "2025-10-01T09:38:37.496Z",
    "state": "IN_PROGRESS",
    "workpieceId": "047b8bca341291",
    "startedAt": "2025-10-01T09:38:37.496Z"
  }
]

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/ccu_order_active__000104.json
[
  {
    "orderType": "STORAGE",
    "type": "RED",
    "timestamp": "2025-10-01T11:16:48.625Z",
    "orderId": "f3ea84df-23c2-4eb4-8872-f2a0b8ba2839",
    "productionSteps": [
      {
        "id": "1c4f7f5a-03aa-42e9-872c-777ed7c30a3c",
        "type": "NAVIGATION",
        "state": "IN_PROGRESS",
        "source": "START",
        "target": "DPS",
        "startedAt": "2025-10-01T11:16:48.785Z"
      },
      {
        "id": "e43ffb1c-9c87-48a8-bb8f-d7cec3237768",
        "type": "MANUFACTURE",
        "dependentActionId": "1c4f7f5a-03aa-42e9-872c-777ed7c30a3c",
        "state": "ENQUEUED",
        "command": "DROP",
        "moduleType": "DPS"
      },
      {
        "id": "715023ca-edcf-4372-801d-17f21e59d2ad",
        "type": "NAVIGATION",
        "state": "ENQUEUED",
        "source": "DPS",
        "target": "HBW",
        "dependentActionId": "e43ffb1c-9c87-48a8-bb8f-d7cec3237768"
      },
      {
        "id": "ed6df615-edbe-4fc0-8339-a5ef175976fe",
        "type": "MANUFACTURE",
        "dependentActionId": "715023ca-edcf-4372-801d-17f21e59d2ad",
        "state": "ENQUEUED",
        "command": "PICK",
        "moduleType": "HBW"
      }
    ],
    "receivedAt": "2025-10-01T11:16:48.727Z",
    "state": "IN_PROGRESS",
    "workpieceId": "04d78cca341290",
    "startedAt": "2025-10-01T11:16:48.728Z"
  }
]

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/ccu_order_active__000352.json
[
  {
    "orderType": "PRODUCTION",
    "type": "RED",
    "timestamp": "2025-10-01T10:12:18.633Z",
    "orderId": "0f77cfd1-c4ec-4e5f-8262-d9de2add939a",
    "productionSteps": [
      {
        "id": "245d9d53-aa2c-4e57-940f-0a0e9078e747",
        "type": "NAVIGATION",
        "state": "IN_PROGRESS",
        "source": "START",
        "target": "HBW",
        "startedAt": "2025-10-01T10:12:18.734Z"
      },
      {
        "id": "261b0b0e-2e36-496c-b023-6f7c3742565b",
        "type": "MANUFACTURE",
        "dependentActionId": "245d9d53-aa2c-4e57-940f-0a0e9078e747",
        "state": "ENQUEUED",
        "command": "DROP",
        "moduleType": "HBW"
      },
      {
        "id": "22efe65d-caab-4cbf-98a6-0965eda5b2ad",
        "type": "NAVIGATION",
        "state": "ENQUEUED",
        "source": "HBW",
        "target": "MILL",
        "dependentActionId": "261b0b0e-2e36-496c-b023-6f7c3742565b"
      },
      {
        "id": "58aefacb-3bf6-4fa1-828d-11bd5a2efbfe",
        "type": "MANUFACTURE",
        "dependentActionId": "22efe65d-caab-4cbf-98a6-0965eda5b2ad",
        "state": "ENQUEUED",
        "command": "PICK",
        "moduleType": "MILL"
      },
      {
        "id": "789ebf8e-6006-4b0f-8483-aa76a5c0b03f",
        "type": "MANUFACTURE",
        "dependentActionId": "58aefacb-3bf6-4fa1-828d-11bd5a2efbfe",
        "state": "ENQUEUED",
        "command": "MILL",
        "moduleType": "MILL"
      },
      {
        "id": "6aaa9fc6-8e13-4535-b514-23aa71e75e31",
        "type": "MANUFACTURE",
        "dependentActionId": "789ebf8e-6006-4b0f-8483-aa76a5c0b03f",
        "state": "ENQUEUED",
        "command": "DROP",
        "moduleType": "MILL"
      },
      {
        "id": "2bbd5b43-07f9-4f67-a633-9aae55d55ab6",
        "type": "NAVIGATION",
        "state": "ENQUEUED",
        "source": "MILL",
        "target": "AIQS",
        "dependentActionId": "6aaa9fc6-8e13-4535-b514-23aa71e75e31"
      },
      {
        "id": "33df923c-4022-441d-a9d5-28a259e80dbe",
        "type": "MANUFACTURE",
        "dependentActionId": "2bbd5b43-07f9-4f67-a633-9aae55d55ab6",
        "state": "ENQUEUED",
        "command": "PICK",
        "moduleType": "AIQS"
      },
      {
        "id": "205375e9-ecb6-43b6-a65d-e8a4d9f8df74",
        "type": "MANUFACTURE",
        "dependentActionId": "33df923c-4022-441d-a9d5-28a259e80dbe",
        "state": "ENQUEUED",
        "command": "CHECK_QUALITY",
        "moduleType": "AIQS"
      },
      {
        "id": "0cc7dab1-648b-4276-80b5-f8d1c35c2cde",
        "type": "MANUFACTURE",
        "dependentActionId": "205375e9-ecb6-43b6-a65d-e8a4d9f8df74",
        "state": "ENQUEUED",
        "command": "DROP",
        "moduleType": "AIQS"
      },
      {
        "id": "0eec2bd5-4d93-40fd-bdf8-a0787bd55ce5",
        "type": "NAVIGATION",
        "state": "ENQUEUED",
        "source": "AIQS",
        "target": "DPS",
        "dependentActionId": "0cc7dab1-648b-4276-80b5-f8d1c35c2cde"
      },
      {
        "id": "5882210b-a66d-436b-a649-afb08b6203f3",
        "type": "MANUFACTURE",
        "dependentActionId": "0eec2bd5-4d93-40fd-bdf8-a0787bd55ce5",
        "state": "ENQUEUED",
        "command": "PICK",
        "moduleType": "DPS"
      }
    ],
    "receivedAt": "2025-10-01T10:12:18.691Z",
    "state": "IN_PROGRESS",
    "startedAt": "2025-10-01T10:12:18.692Z"
  }
]
