=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/ccu_state_calibration_serial.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "timestamp": {
      "type": "string"
    },
    "serialNumber": {
      "type": "string"
    },
    "calibrating": {
      "type": "boolean"
    },
    "references": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "referenceKey": {
            "type": "string"
          },
          "referenceValue": {
            "type": "integer"
          }
        },
        "required": [
          "referenceKey",
          "referenceValue"
        ]
      }
    },
    "status_references": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "referenceKey": {
            "type": "string"
          },
          "referenceValue": {
            "type": "string"
          }
        },
        "required": [
          "referenceKey",
          "referenceValue"
        ]
      }
    }
  },
  "required": [
    "calibrating",
    "serialNumber",
    "timestamp"
  ],
  "title": "Ccu_State_Calibration_Serial Schema",
  "description": "Granular schema for ccu_state_calibration_serial topics from 15 examples",
  "category": "ccu",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/ccu_state_calibration_SVR4H76530__000126.json
{
  "timestamp": "2025-10-01T10:57:12.787Z",
  "serialNumber": "SVR4H76530",
  "calibrating": true,
  "references": [
    {
      "referenceKey": "cal__cameraTime",
      "referenceValue": 745
    },
    {
      "referenceKey": "cal__badTime",
      "referenceValue": 10
    },
    {
      "referenceKey": "cal__processEndTime",
      "referenceValue": 2000
    },
    {
      "referenceKey": "cal__midLightGateTime",
      "referenceValue": 20
    },
    {
      "referenceKey": "cal__gripperDownTime",
      "referenceValue": 700
    },
    {
      "referenceKey": "cal__vacuumReleaseTime",
      "referenceValue": 200
    },
    {
      "referenceKey": "cal__prePhotoTime",
      "referenceValue": 500
    },
    {
      "referenceKey": "cal__vacuumGenerateTime",
      "referenceValue": 200
    },
    {
      "referenceKey": "cal__preFaultCheckTime",
      "referenceValue": 500
    },
    {
      "referenceKey": "cal__defCameraTime",
      "referenceValue": 745
    },
    {
      "referenceKey": "cal__defBadTime",
      "referenceValue": 1000
    },
    {
      "referenceKey": "cal__defProcessEndTime",
      "referenceValue": 2000
    },
    {
      "referenceKey": "cal__defMidLightGateTime",
      "referenceValue": 20
    },
    {
      "referenceKey": "cal__defPrePhotoTime",
      "referenceValue": 500
    },
    {
      "referenceKey": "cal__defGripperDownTime",
      "referenceValue": 700
    },
    {
      "referenceKey": "cal__defVacuumReleaseTime",
      "referenceValue": 200
    },
    {
      "referenceKey": "cal__defPreFaultCheckTime",
      "referenceValue": 500
    },
    {
      "referenceKey": "cal__defVacuumGenerateTime",
      "referenceValue": 200
    }
  ],
  "status_references": [
    {
      "referenceKey": "POSITIONS.AVAILABLE",
      "referenceValue": "TO_CAMERA,TO_NIO_BIN,TO_PICKUP,CALIBRATION_TESTIMAGE"
    },
    {
      "referenceKey": "POSITIONS.CURRENT",
      "referenceValue": "TO_PICKUP"
    }
  ]
}
