=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/fts_v1_ff_serial_state.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "lastNodeSequenceId": {
      "type": "integer"
    },
    "batteryState": {
      "type": "object",
      "properties": {
        "currentVoltage": {
          "type": "number"
        },
        "percentage": {
          "type": "integer"
        },
        "maxVolt": {
          "type": "number"
        },
        "charging": {
          "type": "boolean"
        },
        "minVolt": {
          "type": "number"
        }
      },
      "required": [
        "charging",
        "currentVoltage",
        "maxVolt",
        "minVolt",
        "percentage"
      ]
    },
    "timestamp": {
      "type": "string"
    },
    "serialNumber": {
      "type": "string"
    },
    "driving": {
      "type": "boolean"
    },
    "paused": {
      "type": "boolean"
    },
    "errors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "errorLevel": {
            "type": "string"
          },
          "errorType": {
            "type": "string"
          },
          "errorReferences": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "referenceValue": {
                  "type": [
                    "integer",
                    "null",
                    "string"
                  ]
                },
                "referenceKey": {
                  "type": "string"
                }
              },
              "required": [
                "referenceKey",
                "referenceValue"
              ]
            }
          }
        },
        "required": [
          "errorLevel",
          "errorReferences",
          "errorType"
        ]
      }
    },
    "orderId": {
      "type": "string"
    },
    "orderUpdateId": {
      "type": "integer"
    },
    "lastNodeId": {
      "type": "string"
    },
    "lastCode": {
      "type": "string"
    },
    "waitingForLoadHandling": {
      "type": "boolean"
    },
    "actionStates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "timestamp": {
            "type": "string"
          },
          "command": {
            "type": "string"
          }
        },
        "required": [
          "command",
          "id",
          "state",
          "timestamp"
        ]
      }
    },
    "edgeStates": {
      "type": "array"
    },
    "headerId": {
      "type": "integer"
    },
    "load": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "loadPosition": {
            "type": "string"
          },
          "loadType": {
            "type": [
              "null",
              "string"
            ]
          },
          "loadId": {
            "type": [
              "null",
              "string"
            ]
          }
        },
        "required": [
          "loadId",
          "loadPosition",
          "loadType"
        ]
      }
    },
    "nodeStates": {
      "type": "array"
    },
    "actionState": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "command": {
          "type": "string"
        }
      },
      "required": [
        "command",
        "id",
        "state",
        "timestamp"
      ]
    }
  },
  "required": [
    "actionStates",
    "batteryState",
    "driving",
    "edgeStates",
    "errors",
    "headerId",
    "lastCode",
    "lastNodeId",
    "lastNodeSequenceId",
    "load",
    "nodeStates",
    "orderId",
    "orderUpdateId",
    "paused",
    "serialNumber",
    "timestamp",
    "waitingForLoadHandling"
  ],
  "title": "Fts_V1_Ff_Serial_State Schema",
  "description": "Granular schema for fts_v1_ff_serial_state topics from 112 examples",
  "category": "fts",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/fts_v1_ff_5iO4_state__000319.json
{
  "actionState": {
    "id": "80d11088-e361-4617-b04f-d946e900f313",
    "state": "FINISHED",
    "timestamp": "2025-10-01T09:39:33.904681Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:39:45.082628Z",
  "actionStates": [
    {
      "id": "c553bbb5-0f28-4dfc-8fa7-32cd5fddce9b",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:39:24.236023Z",
      "command": "TURN"
    },
    {
      "id": "1077bdc0-e9cf-4c87-8145-e177dbfeaa70",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:39:27.856492Z",
      "command": "TURN"
    },
    {
      "id": "80d11088-e361-4617-b04f-d946e900f313",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:39:33.904681Z",
      "command": "DOCK"
    },
    {
      "id": "784fcbdb-2aea-40ae-9431-a4f95d610ebe",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:39:45.082285Z",
      "command": "clearLoadHandler"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
  "edgeStates": [],
  "load": [
    {
      "loadType": null,
      "loadId": null,
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR4H76449",
  "nodeStates": [],
  "headerId": 346,
  "driving": false,
  "orderUpdateId": 2,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_state__000054.json
{
  "actionState": {
    "id": "ce016d78-4598-4752-bbf6-f1cc69d1f311",
    "state": "WAITING",
    "timestamp": "2025-10-01T09:53:52.283538Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:53:52.281460Z",
  "actionStates": [
    {
      "id": "ce016d78-4598-4752-bbf6-f1cc69d1f311",
      "state": "WAITING",
      "timestamp": "2025-10-01T09:53:52.281804Z",
      "command": "DOCK"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "5e0cc980-785a-44fc-a690-3e3ac2eaabd3",
  "edgeStates": [],
  "load": [
    {
      "loadType": null,
      "loadId": null,
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR4H73275",
  "nodeStates": [],
  "headerId": 389,
  "driving": false,
  "orderUpdateId": 0,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}
