=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/fts_v1_ff_serial_factsheet.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "version": {
      "type": "string"
    },
    "timestamp": {
      "type": "string"
    },
    "localizationParameters": {
      "type": "object"
    },
    "serialNumber": {
      "type": "string"
    },
    "physicalParameters": {
      "type": "object"
    },
    "protocolLimits": {
      "type": "object"
    },
    "typeSpecification": {
      "type": "object",
      "properties": {
        "agvClass": {
          "type": "string"
        },
        "seriesName": {
          "type": "string"
        },
        "navigationTypes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "agvClass",
        "navigationTypes",
        "seriesName"
      ]
    },
    "agvGeometry": {
      "type": "object"
    },
    "manufacturer": {
      "type": "string"
    },
    "protocolFeatures": {
      "type": "object",
      "properties": {
        "agvActions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "actionType": {
                "type": "string"
              },
              "actionScopes": {
                "type": "string"
              }
            },
            "required": [
              "actionScopes",
              "actionType"
            ]
          }
        }
      },
      "required": [
        "agvActions"
      ]
    },
    "loadSpecification": {
      "type": "object",
      "properties": {
        "loadPositions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "loadSets": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "loadType": {
                "type": "string"
              },
              "setName": {
                "type": "string"
              }
            },
            "required": [
              "loadType",
              "setName"
            ]
          }
        }
      },
      "required": [
        "loadPositions",
        "loadSets"
      ]
    },
    "headerId": {
      "type": "integer"
    }
  },
  "required": [
    "agvGeometry",
    "headerId",
    "loadSpecification",
    "localizationParameters",
    "manufacturer",
    "physicalParameters",
    "protocolFeatures",
    "protocolLimits",
    "serialNumber",
    "timestamp",
    "typeSpecification",
    "version"
  ],
  "title": "Fts_V1_Ff_Serial_Factsheet Schema",
  "description": "Granular schema for fts_v1_ff_serial_factsheet topics from 2 examples",
  "category": "fts",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/integrations/fischertechnik-txt-programs/fts_main/fts_main-master/data/factsheet.json
{
    "headerId": 1,
    "timestamp": "<replace_in_vda5050>",
    "version": "1.1.0+git250d287",
    "manufacturer": "Fischertechnik",
    "serialNumber": "<replace_in_vda5050>",
    "typeSpecification": {
        "seriesName": "FTS-FF22+",
        "agvClass": "CARRIER",
        "navigationTypes": [
            "PHYSICAL_LINE_GUIDED"
        ]
    },
    "physicalParameters": {},
    "protocolLimits": {},
    "protocolFeatures": {
        "agvActions": [
            {
                "actionType": "DOCK",
                "actionScopes": "NODE"
            }
        ]
    },
    "agvGeometry": {},
    "localizationParameters": {},
    "loadSpecification": {
        "loadPositions": [
            "LEFT",
            "MIDDLE",
            "RIGHT"
        ],
        "loadSets": [
            {
                "setName": "WHITES",
                "loadType": "WHITE"
            },
            {
                "setName": "REDS",
                "loadType": "RED"
            },
            {
                "setName": "BLUES",
                "loadType": "BLUE"
            }
        ]
    }
}
