=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/fts_v1_ff_serial_order.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "timestamp": {
      "type": "string"
    },
    "orderId": {
      "type": "string"
    },
    "orderUpdateId": {
      "type": "integer"
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "linkedEdges": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "action": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "metadata": {
                "type": "object",
                "properties": {
                  "direction": {
                    "type": "string"
                  },
                  "loadType": {
                    "type": "string"
                  },
                  "loadPosition": {
                    "type": "string"
                  },
                  "loadId": {
                    "type": "string"
                  },
                  "charge": {
                    "type": "boolean"
                  }
                }
              }
            },
            "required": [
              "id",
              "type"
            ]
          }
        },
        "required": [
          "id",
          "linkedEdges"
        ]
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "length": {
            "type": "integer"
          },
          "linkedNodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "id",
          "length",
          "linkedNodes"
        ]
      }
    },
    "serialNumber": {
      "type": "string"
    }
  },
  "required": [
    "edges",
    "nodes",
    "orderId",
    "orderUpdateId",
    "serialNumber",
    "timestamp"
  ],
  "title": "Fts_V1_Ff_Serial_Order Schema",
  "description": "Granular schema for fts_v1_ff_serial_order topics from 51 examples",
  "category": "fts",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_order__000372.json
{
  "timestamp": "2025-10-01T10:13:15.716Z",
  "orderId": "0f77cfd1-c4ec-4e5f-8262-d9de2add939a",
  "orderUpdateId": 2,
  "nodes": [
    {
      "id": "SVR3QA0022",
      "linkedEdges": [
        "SVR3QA0022-1"
      ]
    },
    {
      "id": "1",
      "linkedEdges": [
        "SVR3QA0022-1",
        "1-SVR3QA2098"
      ],
      "action": {
        "id": "9b636a73-5591-4bc7-95d3-26d33fe07491",
        "type": "TURN",
        "metadata": {
          "direction": "LEFT"
        }
      }
    },
    {
      "id": "SVR3QA2098",
      "linkedEdges": [
        "1-SVR3QA2098"
      ],
      "action": {
        "type": "DOCK",
        "id": "22efe65d-caab-4cbf-98a6-0965eda5b2ad",
        "metadata": {
          "loadId": "04fa8cca341290",
          "loadType": "RED",
          "loadPosition": "1"
        }
      }
    }
  ],
  "edges": [
    {
      "id": "SVR3QA0022-1",
      "length": 380,
      "linkedNodes": [
        "SVR3QA0022",
        "1"
      ]
    },
    {
      "id": "1-SVR3QA2098",
      "length": 380,
      "linkedNodes": [
        "1",
        "SVR3QA2098"
      ]
    }
  ],
  "serialNumber": "5iO4"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_order__000221.json
{
  "timestamp": "2025-10-01T11:38:08.945Z",
  "orderId": "06dbdb8a-311e-4cf0-b76d-1366317cbccc",
  "orderUpdateId": 0,
  "nodes": [
    {
      "id": "SVR4H76530",
      "linkedEdges": [
        "SVR4H76530-2"
      ]
    },
    {
      "id": "2",
      "linkedEdges": [
        "SVR4H76530-2",
        "2-1"
      ],
      "action": {
        "id": "4306d3b6-dd65-444b-807c-98c9591080b7",
        "type": "TURN",
        "metadata": {
          "direction": "RIGHT"
        }
      }
    },
    {
      "id": "1",
      "linkedEdges": [
        "2-1",
        "1-SVR3QA0022"
      ],
      "action": {
        "id": "78cd45e4-bc71-4f20-9101-eaa2bdcbf24f",
        "type": "PASS"
      }
    },
    {
      "id": "SVR3QA0022",
      "linkedEdges": [
        "1-SVR3QA0022"
      ],
      "action": {
        "type": "DOCK",
        "id": "f18b9cbe-cfa4-414c-bfa5-547af27ef169",
        "metadata": {
          "loadType": "RED",
          "loadPosition": "1"
        }
      }
    }
  ],
  "edges": [
    {
      "id": "SVR4H76530-2",
      "length": 380,
      "linkedNodes": [
        "SVR4H76530",
        "2"
      ]
    },
    {
      "id": "2-1",
      "length": 360,
      "linkedNodes": [
        "2",
        "1"
      ]
    },
    {
      "id": "1-SVR3QA0022",
      "length": 380,
      "linkedNodes": [
        "1",
        "SVR3QA0022"
      ]
    }
  ],
  "serialNumber": "5iO4"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/fts_v1_ff_5iO4_order__000161.json
{
  "timestamp": "2025-10-01T11:36:10.175Z",
  "orderId": "1aacf6d8-31be-42d5-9adf-162e0b7c768b",
  "orderUpdateId": 0,
  "nodes": [
    {
      "id": "SVR3QA0022",
      "linkedEdges": [],
      "action": {
        "type": "DOCK",
        "id": "be345d91-d09d-4f70-88bc-9ee4ae72fc83",
        "metadata": {
          "loadType": "RED",
          "loadPosition": "1"
        }
      }
    }
  ],
  "edges": [],
  "serialNumber": "5iO4"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/fts_v1_ff_5iO4_order__000047.json
{
  "timestamp": "2025-10-01T09:58:06.927Z",
  "orderId": "50fdbb01-1cf6-45c1-a24b-7171f9cab3e2",
  "orderUpdateId": 0,
  "nodes": [
    {
      "id": "SVR3QA0022",
      "linkedEdges": [
        "SVR3QA0022-1"
      ]
    },
    {
      "id": "1",
      "linkedEdges": [
        "SVR3QA0022-1",
        "1-2"
      ],
      "action": {
        "id": "9ac80fff-2088-49d9-82ab-a1930f8ef421",
        "type": "PASS"
      }
    },
    {
      "id": "2",
      "linkedEdges": [
        "1-2",
        "2-SVR4H73275"
      ],
      "action": {
        "id": "a40c4cee-adeb-4435-8b7a-e43b06c8a9c4",
        "type": "PASS"
      }
    },
    {
      "id": "SVR4H73275",
      "linkedEdges": [
        "2-SVR4H73275"
      ],
      "action": {
        "type": "DOCK",
        "id": "320d2896-8d0e-44e2-8122-d9ba45384fc4",
        "metadata": {
          "loadId": "040a8dca341291",
          "loadType": "RED",
          "loadPosition": "1"
        }
      }
    }
  ],
  "edges": [
    {
      "id": "SVR3QA0022-1",
      "length": 380,
      "linkedNodes": [
        "SVR3QA0022",
        "1"
      ]
    },
    {
      "id": "1-2",
      "length": 360,
      "linkedNodes": [
        "1",
        "2"
      ]
    },
    {
      "id": "2-SVR4H73275",
      "length": 380,
      "linkedNodes": [
        "2",
        "SVR4H73275"
      ]
    }
  ],
  "serialNumber": "5iO4"
}
