=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/fts_v1_ff_serial_state.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "lastNodeSequenceId": {
      "type": "integer"
    },
    "batteryState": {
      "type": "object",
      "properties": {
        "currentVoltage": {
          "type": "number"
        },
        "percentage": {
          "type": "integer"
        },
        "maxVolt": {
          "type": "number"
        },
        "charging": {
          "type": "boolean"
        },
        "minVolt": {
          "type": "number"
        }
      },
      "required": [
        "charging",
        "currentVoltage",
        "maxVolt",
        "minVolt",
        "percentage"
      ]
    },
    "timestamp": {
      "type": "string"
    },
    "serialNumber": {
      "type": "string"
    },
    "driving": {
      "type": "boolean"
    },
    "paused": {
      "type": "boolean"
    },
    "errors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "errorLevel": {
            "type": "string"
          },
          "errorType": {
            "type": "string"
          },
          "errorReferences": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "referenceValue": {
                  "type": [
                    "integer",
                    "null",
                    "string"
                  ]
                },
                "referenceKey": {
                  "type": "string"
                }
              },
              "required": [
                "referenceKey",
                "referenceValue"
              ]
            }
          }
        },
        "required": [
          "errorLevel",
          "errorReferences",
          "errorType"
        ]
      }
    },
    "orderId": {
      "type": "string"
    },
    "orderUpdateId": {
      "type": "integer"
    },
    "lastNodeId": {
      "type": "string"
    },
    "lastCode": {
      "type": "string"
    },
    "waitingForLoadHandling": {
      "type": "boolean"
    },
    "actionStates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "timestamp": {
            "type": "string"
          },
          "command": {
            "type": "string"
          }
        },
        "required": [
          "command",
          "id",
          "state",
          "timestamp"
        ]
      }
    },
    "edgeStates": {
      "type": "array"
    },
    "headerId": {
      "type": "integer"
    },
    "load": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "loadPosition": {
            "type": "string"
          },
          "loadType": {
            "type": [
              "null",
              "string"
            ]
          },
          "loadId": {
            "type": [
              "null",
              "string"
            ]
          }
        },
        "required": [
          "loadId",
          "loadPosition",
          "loadType"
        ]
      }
    },
    "nodeStates": {
      "type": "array"
    },
    "actionState": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "command": {
          "type": "string"
        }
      },
      "required": [
        "command",
        "id",
        "state",
        "timestamp"
      ]
    }
  },
  "required": [
    "actionStates",
    "batteryState",
    "driving",
    "edgeStates",
    "errors",
    "headerId",
    "lastCode",
    "lastNodeId",
    "lastNodeSequenceId",
    "load",
    "nodeStates",
    "orderId",
    "orderUpdateId",
    "paused",
    "serialNumber",
    "timestamp",
    "waitingForLoadHandling"
  ],
  "title": "Fts_V1_Ff_Serial_State Schema",
  "description": "Granular schema for fts_v1_ff_serial_state topics from 112 examples",
  "category": "fts",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/fts_v1_ff_5iO4_state__000072.json
{
  "actionState": {
    "id": "ce016d78-4598-4752-bbf6-f1cc69d1f311",
    "state": "FINISHED",
    "timestamp": "2025-10-01T09:53:54.198784Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:54:09.438785Z",
  "actionStates": [
    {
      "id": "ce016d78-4598-4752-bbf6-f1cc69d1f311",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:53:54.198784Z",
      "command": "DOCK"
    },
    {
      "id": "11f89bec-d56d-43c6-bf5b-1a28944cc3cf",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:54:09.438446Z",
      "command": "clearLoadHandler"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "5e0cc980-785a-44fc-a690-3e3ac2eaabd3",
  "edgeStates": [],
  "load": [
    {
      "loadType": "WHITE",
      "loadId": "047b8bca341291",
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR4H73275",
  "nodeStates": [],
  "headerId": 394,
  "driving": false,
  "orderUpdateId": 0,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_state__000146.json
{
  "actionState": {
    "id": "897998c8-a417-44b6-9e7d-3e0b21ceb9e7",
    "state": "RUNNING",
    "timestamp": "2025-10-01T09:36:24.083957Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:36:24.084308Z",
  "actionStates": [
    {
      "id": "897998c8-a417-44b6-9e7d-3e0b21ceb9e7",
      "state": "RUNNING",
      "timestamp": "2025-10-01T09:36:24.083957Z",
      "command": "DOCK"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "5e75ef1f-6091-4ec0-b71c-4d54968593f9",
  "edgeStates": [],
  "load": [],
  "lastNodeId": "SVR4H73275",
  "nodeStates": [],
  "headerId": 307,
  "driving": true,
  "orderUpdateId": 0,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_state__000250.json
{
  "actionState": {
    "id": "045c08f2-dc8a-4bfc-923c-6aaacd60237a",
    "state": "INITIALIZING",
    "timestamp": "2025-10-01T09:38:37.705562Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:38:37.706464Z",
  "actionStates": [
    {
      "id": "045c08f2-dc8a-4bfc-923c-6aaacd60237a",
      "state": "INITIALIZING",
      "timestamp": "2025-10-01T09:38:37.705562Z",
      "command": "DOCK"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
  "edgeStates": [],
  "load": [
    {
      "loadType": null,
      "loadId": null,
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR3QA0022",
  "nodeStates": [],
  "headerId": 324,
  "driving": true,
  "orderUpdateId": 0,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_state__000037.json
{
  "actionState": {
    "id": "0de94daf-92ec-4bda-8332-ac3d6ad149fb",
    "state": "FINISHED",
    "timestamp": "2025-10-01T08:35:18.602037Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:32:53.097948Z",
  "actionStates": [
    {
      "id": "35e4f0fa-7bfd-4b7c-ab6a-89f48a2206bc",
      "state": "FINISHED",
      "timestamp": "2025-10-01T08:35:12.994338Z",
      "command": "TURN"
    },
    {
      "id": "0de94daf-92ec-4bda-8332-ac3d6ad149fb",
      "state": "FINISHED",
      "timestamp": "2025-10-01T08:35:18.602037Z",
      "command": "DOCK"
    },
    {
      "id": "512734e7-03ba-4f8b-915c-087c60d102d0",
      "state": "FINISHED",
      "timestamp": "2025-10-01T08:35:42.231509Z",
      "command": "clearLoadHandler"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "591be086-e66f-4633-8496-e19ade9d414b",
  "edgeStates": [],
  "load": [
    {
      "loadType": null,
      "loadId": null,
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR4H73275",
  "nodeStates": [],
  "headerId": 298,
  "driving": false,
  "orderUpdateId": 14,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/fts_v1_ff_5iO4_state__000401.json
{
  "actionState": {
    "id": "06d04f01-df74-4fda-a77b-2718c9dd9947",
    "state": "FINISHED",
    "timestamp": "2025-10-01T09:40:23.012289Z",
    "command": "DOCK"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:40:48.514030Z",
  "actionStates": [
    {
      "id": "bddbbd1f-afa3-491e-9bbc-ecff1cd8de87",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:40:08.577022Z",
      "command": "TURN"
    },
    {
      "id": "52442406-6770-40ae-97ae-4f5f8a0fd7cd",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:40:13.730341Z",
      "command": "TURN"
    },
    {
      "id": "1f355918-e8fe-4b49-8c7e-70880a3c79ab",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:40:17.342273Z",
      "command": "TURN"
    },
    {
      "id": "06d04f01-df74-4fda-a77b-2718c9dd9947",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:40:23.012289Z",
      "command": "DOCK"
    },
    {
      "id": "4fb07a21-b604-41bb-b8a2-df5dbddae929",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:40:31.435998Z",
      "command": "clearLoadHandler"
    },
    {
      "id": "fd9018e8-8390-4fd3-815a-97523ee179fa",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:40:48.513622Z",
      "command": "clearLoadHandler"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
  "edgeStates": [],
  "load": [
    {
      "loadType": "WHITE",
      "loadId": "047b8bca341291",
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR4H76530",
  "nodeStates": [],
  "headerId": 372,
  "driving": false,
  "orderUpdateId": 6,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/fts_v1_ff_5iO4_state__000291.json
{
  "actionState": {
    "id": "c553bbb5-0f28-4dfc-8fa7-32cd5fddce9b",
    "state": "FINISHED",
    "timestamp": "2025-10-01T09:39:24.236023Z",
    "command": "TURN"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:39:24.236629Z",
  "actionStates": [
    {
      "id": "c553bbb5-0f28-4dfc-8fa7-32cd5fddce9b",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:39:24.236023Z",
      "command": "TURN"
    },
    {
      "id": "1077bdc0-e9cf-4c87-8145-e177dbfeaa70",
      "state": "WAITING",
      "timestamp": "2025-10-01T09:39:24.237135Z",
      "command": "TURN"
    },
    {
      "id": "80d11088-e361-4617-b04f-d946e900f313",
      "state": "WAITING",
      "timestamp": "2025-10-01T09:39:24.237307Z",
      "command": "DOCK"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
  "edgeStates": [],
  "load": [
    {
      "loadType": "WHITE",
      "loadId": "047b8bca341291",
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "1",
  "nodeStates": [],
  "headerId": 334,
  "driving": true,
  "orderUpdateId": 2,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_state__000107.json
{
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:35:42.403209Z",
  "actionStates": [
    {
      "id": "1de2c1b5-1ae0-405b-a0fe-388f6f858604",
      "state": "FINISHED",
      "timestamp": "2025-10-01T09:35:42.402869Z",
      "command": "findInitialDockPosition"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "",
  "edgeStates": [],
  "load": [],
  "lastNodeId": "SVR4H73275",
  "nodeStates": [],
  "headerId": 303,
  "driving": true,
  "orderUpdateId": 0,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 84,
    "currentVoltage": 8.9
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/fts_v1_ff_5iO4_state__000404.json
{
  "actionState": {
    "id": "e8e0aced-aefe-4f8b-bb2b-7f3c07ed0d1c",
    "state": "WAITING",
    "timestamp": "2025-10-01T09:40:48.687212Z",
    "command": "TURN"
  },
  "serialNumber": "5iO4",
  "waitingForLoadHandling": false,
  "timestamp": "2025-10-01T09:40:48.686185Z",
  "actionStates": [
    {
      "id": "e8e0aced-aefe-4f8b-bb2b-7f3c07ed0d1c",
      "state": "WAITING",
      "timestamp": "2025-10-01T09:40:48.686659Z",
      "command": "TURN"
    },
    {
      "id": "53eff382-aa9b-4b76-8223-b41761e93a35",
      "state": "WAITING",
      "timestamp": "2025-10-01T09:40:48.686918Z",
      "command": "DOCK"
    }
  ],
  "lastNodeSequenceId": 0,
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
  "edgeStates": [],
  "load": [
    {
      "loadType": "WHITE",
      "loadId": "047b8bca341291",
      "loadPosition": "1"
    }
  ],
  "lastNodeId": "SVR4H76530",
  "nodeStates": [],
  "headerId": 374,
  "driving": true,
  "orderUpdateId": 10,
  "errors": [],
  "lastCode": "",
  "paused": false,
  "batteryState": {
    "charging": false,
    "maxVolt": 9.1,
    "minVolt": 7.84,
    "percentage": 76,
    "currentVoltage": 8.8
  }
}
