=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/module_v1_ff_NodeRed_serial_state.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "errors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "errorLevel": {
            "type": "string"
          },
          "errorReferences": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "orderId": {
                  "type": [
                    "null",
                    "string"
                  ]
                },
                "topic": {
                  "type": "string"
                },
                "headerId": {
                  "type": "null"
                },
                "orderUpdateId": {
                  "type": "integer"
                }
              }
            }
          },
          "errorType": {
            "type": "string"
          }
        },
        "required": [
          "errorLevel",
          "errorReferences",
          "errorType"
        ]
      }
    },
    "orderId": {
      "type": "string"
    },
    "headerId": {
      "type": "integer"
    },
    "orderUpdateId": {
      "type": "integer"
    },
    "timestamp": {
      "type": "string"
    },
    "batteryState": {
      "type": "object"
    },
    "serialNumber": {
      "type": "string"
    },
    "actionState": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "properties": {
            "command": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "timestamp": {
              "type": "string"
            },
            "result": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "command",
            "id",
            "state",
            "timestamp"
          ]
        }
      ]
    },
    "paused": {
      "type": "boolean"
    },
    "operatingMode": {
      "type": "string"
    },
    "information": {
      "type": "array"
    },
    "actionStates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "properties": {
              "workpiece": {
                "type": "object",
                "properties": {
                  "workpieceId": {
                    "type": "string"
                  },
                  "history": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "integer"
                        },
                        "ts": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "code",
                        "ts"
                      ]
                    }
                  },
                  "type": {
                    "type": "string"
                  },
                  "state": {
                    "type": "string"
                  }
                },
                "required": [
                  "history",
                  "state",
                  "type",
                  "workpieceId"
                ]
              },
              "type": {
                "type": "string"
              }
            }
          },
          "state": {
            "type": "string"
          },
          "command": {
            "type": "string"
          },
          "result": {
            "type": [
              "null",
              "string"
            ]
          },
          "warning": {
            "type": "boolean"
          }
        },
        "required": [
          "command",
          "id",
          "state"
        ]
      }
    }
  },
  "required": [
    "actionState",
    "batteryState",
    "errors",
    "headerId",
    "orderId",
    "orderUpdateId",
    "paused",
    "serialNumber",
    "timestamp"
  ],
  "title": "Module_V1_Ff_Nodered_Serial_State Schema",
  "description": "Granular schema for module_v1_ff_NodeRed_serial_state topics from 170 examples",
  "category": "module",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H76530_state__000408.json
{
  "headerId": 24,
  "serialNumber": "SVR4H76530",
  "paused": false,
  "actionState": {
    "result": "FAILED",
    "id": "205375e9-ecb6-43b6-a65d-e8a4d9f8df74",
    "timestamp": "2025-10-01T10:14:18.791906Z",
    "command": "CHECK_QUALITY",
    "state": "RUNNING"
  },
  "timestamp": "2025-10-01T10:14:21.953063Z",
  "batteryState": {},
  "orderUpdateId": 10,
  "errors": [],
  "orderId": "0f77cfd1-c4ec-4e5f-8262-d9de2add939a"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000078.json
{
  "actionStates": [],
  "actionState": null,
  "batteryState": {},
  "errors": [
    {
      "errorLevel": "WARNING",
      "errorReferences": [
        {
          "orderId": null
        }
      ],
      "errorType": "RESET_WARNING"
    }
  ],
  "orderUpdateId": 0,
  "paused": false,
  "information": [],
  "operatingMode": "AUTOMATIC",
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T09:35:06.718066Z",
  "headerId": 28,
  "orderId": ""
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000067.json
{
  "headerId": 5,
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T11:32:28.026854Z",
  "paused": false,
  "batteryState": {},
  "operatingMode": "AUTOMATIC",
  "errors": [],
  "orderUpdateId": 1,
  "information": [],
  "actionState": {
    "result": null,
    "id": "3a17e722-68bc-49c2-b1c6-6d20948d9107",
    "timestamp": "2025-10-01T11:32:28.026572Z",
    "state": "FINISHED",
    "command": "INPUT_RGB"
  },
  "orderId": "3a17e722-68bc-49c2-b1c6-6d20948d9107",
  "actionStates": [
    {
      "metadata": {},
      "timestamp": "2025-10-01T11:32:28.026572Z",
      "command": "INPUT_RGB",
      "result": null,
      "id": "3a17e722-68bc-49c2-b1c6-6d20948d9107",
      "state": "FINISHED"
    }
  ]
}
