=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/module_v1_ff_NodeRed_serial_state.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "errors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "errorLevel": {
            "type": "string"
          },
          "errorReferences": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "orderId": {
                  "type": [
                    "null",
                    "string"
                  ]
                },
                "topic": {
                  "type": "string"
                },
                "headerId": {
                  "type": "null"
                },
                "orderUpdateId": {
                  "type": "integer"
                }
              }
            }
          },
          "errorType": {
            "type": "string"
          }
        },
        "required": [
          "errorLevel",
          "errorReferences",
          "errorType"
        ]
      }
    },
    "orderId": {
      "type": "string"
    },
    "headerId": {
      "type": "integer"
    },
    "orderUpdateId": {
      "type": "integer"
    },
    "timestamp": {
      "type": "string"
    },
    "batteryState": {
      "type": "object"
    },
    "serialNumber": {
      "type": "string"
    },
    "actionState": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "properties": {
            "command": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "timestamp": {
              "type": "string"
            },
            "result": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "command",
            "id",
            "state",
            "timestamp"
          ]
        }
      ]
    },
    "paused": {
      "type": "boolean"
    },
    "operatingMode": {
      "type": "string"
    },
    "information": {
      "type": "array"
    },
    "actionStates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "properties": {
              "workpiece": {
                "type": "object",
                "properties": {
                  "workpieceId": {
                    "type": "string"
                  },
                  "history": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "integer"
                        },
                        "ts": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "code",
                        "ts"
                      ]
                    }
                  },
                  "type": {
                    "type": "string"
                  },
                  "state": {
                    "type": "string"
                  }
                },
                "required": [
                  "history",
                  "state",
                  "type",
                  "workpieceId"
                ]
              },
              "type": {
                "type": "string"
              }
            }
          },
          "state": {
            "type": "string"
          },
          "command": {
            "type": "string"
          },
          "result": {
            "type": [
              "null",
              "string"
            ]
          },
          "warning": {
            "type": "boolean"
          }
        },
        "required": [
          "command",
          "id",
          "state"
        ]
      }
    }
  },
  "required": [
    "actionState",
    "batteryState",
    "errors",
    "headerId",
    "orderId",
    "orderUpdateId",
    "paused",
    "serialNumber",
    "timestamp"
  ],
  "title": "Module_V1_Ff_Nodered_Serial_State Schema",
  "description": "Granular schema for module_v1_ff_NodeRed_serial_state topics from 170 examples",
  "category": "module",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000123.json
{
  "actionStates": [
    {
      "state": "RUNNING",
      "command": "RGB_NFC",
      "id": "0",
      "timestamp": "2025-10-01T09:36:06.057906Z",
      "metadata": {
        "type": "BLUE"
      }
    }
  ],
  "actionState": {
    "command": "RGB_NFC",
    "id": "0",
    "timestamp": "2025-10-01T09:36:06.057906Z",
    "state": "RUNNING"
  },
  "batteryState": {},
  "errors": [],
  "orderUpdateId": 1,
  "paused": false,
  "information": [],
  "operatingMode": "AUTOMATIC",
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T09:36:06.058183Z",
  "headerId": 34,
  "orderId": "0"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000425.json
{
  "actionStates": [
    {
      "state": "WAITIING",
      "command": "PICK",
      "id": "63a451a9-f6d2-4008-869e-0e588469e1f2",
      "timestamp": "2025-10-01T09:40:57.998409Z",
      "metadata": {
        "workpiece": {
          "type": "WHITE",
          "workpieceId": "047b8bca341291",
          "state": "PROCESSED",
          "history": [
            {
              "ts": 1759311560402,
              "code": 400
            },
            {
              "ts": 1759311593910,
              "code": 700
            },
            {
              "ts": 1759311639326,
              "code": 200
            }
          ]
        }
      }
    }
  ],
  "actionState": {
    "command": "PICK",
    "id": "63a451a9-f6d2-4008-869e-0e588469e1f2",
    "timestamp": "2025-10-01T09:40:57.998409Z",
    "state": "WAITIING"
  },
  "batteryState": {},
  "errors": [],
  "orderUpdateId": 11,
  "paused": false,
  "information": [],
  "operatingMode": "AUTOMATIC",
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T09:40:57.998740Z",
  "headerId": 39,
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000035.json
{
  "actionStates": [
    {
      "result": null,
      "id": "e3986f6b-cd86-475c-a460-7ce0df43e509",
      "timestamp": "2025-10-01T11:14:29.625888Z",
      "metadata": {},
      "command": "INPUT_RGB",
      "state": "FINISHED"
    }
  ],
  "actionState": {
    "result": null,
    "command": "INPUT_RGB",
    "id": "e3986f6b-cd86-475c-a460-7ce0df43e509",
    "timestamp": "2025-10-01T11:14:29.625888Z",
    "state": "FINISHED"
  },
  "batteryState": {},
  "errors": [],
  "orderUpdateId": 1,
  "paused": false,
  "information": [],
  "operatingMode": "AUTOMATIC",
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T11:14:29.626195Z",
  "headerId": 94,
  "orderId": "e3986f6b-cd86-475c-a460-7ce0df43e509"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000016.json
{
  "actionStates": [
    {
      "command": "factsheetRequest",
      "id": "SOME_ID",
      "state": "FINISHED"
    }
  ],
  "actionState": {
    "command": "factsheetRequest",
    "id": "SOME_ID",
    "timestamp": "2025-10-01T10:46:59.506636Z",
    "state": "FINISHED"
  },
  "batteryState": {},
  "errors": [
    {
      "errorLevel": "WARNING",
      "errorReferences": [
        {
          "orderId": ""
        }
      ],
      "errorType": "RESET_WARNING"
    }
  ],
  "orderUpdateId": 0,
  "paused": false,
  "information": [],
  "operatingMode": "AUTOMATIC",
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T10:46:59.505886Z",
  "headerId": 88,
  "orderId": ""
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H76530_state__000278.json
{
  "errors": [],
  "headerId": 10,
  "orderId": "5acf1a80-07e7-4c80-a128-e6739e681665",
  "timestamp": "2025-10-01T11:23:38.178084Z",
  "orderUpdateId": 10,
  "batteryState": {},
  "serialNumber": "SVR4H76530",
  "actionState": {
    "command": "CHECK_QUALITY",
    "state": "FINISHED",
    "result": "FAILED",
    "timestamp": "2025-10-01T11:23:38.177748Z",
    "id": "3e3b9dd0-906b-4ea3-9a8e-37a8acca0c5d"
  },
  "paused": false
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H73275_state__000213.json
{
  "actionStates": [
    {
      "result": "PASSED",
      "id": "1021192a-0dc9-4ee1-9251-48951415354e",
      "timestamp": "2025-10-01T11:20:59.666495Z",
      "metadata": {
        "workpiece": {
          "type": "RED",
          "workpieceId": "040a8dca341291",
          "state": "PROCESSED",
          "history": [
            {
              "ts": 1759317548792,
              "code": 400
            },
            {
              "ts": 1759317578216,
              "code": 600
            },
            {
              "ts": 1759317619102,
              "code": 200
            }
          ]
        }
      },
      "command": "PICK",
      "state": "FINISHED"
    }
  ],
  "actionState": {
    "result": "PASSED",
    "command": "PICK",
    "id": "1021192a-0dc9-4ee1-9251-48951415354e",
    "timestamp": "2025-10-01T11:20:59.666495Z",
    "state": "FINISHED"
  },
  "batteryState": {},
  "errors": [],
  "orderUpdateId": 11,
  "paused": false,
  "information": [],
  "operatingMode": "AUTOMATIC",
  "serialNumber": "SVR4H73275",
  "timestamp": "2025-10-01T11:20:59.666782Z",
  "headerId": 118,
  "orderId": "aa74c367-dfc6-4c3b-b669-af293ea717f1"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H76530_state__000135.json
{
  "headerId": 48,
  "serialNumber": "SVR4H76530",
  "paused": false,
  "actionState": {
    "result": "FAILED",
    "id": "CHECK_QUALITY__1759316235998",
    "timestamp": "2025-10-01T10:57:20.002655Z",
    "command": "CHECK_QUALITY",
    "state": "FINISHED"
  },
  "timestamp": "2025-10-01T10:57:20.003037Z",
  "batteryState": {},
  "orderUpdateId": 7,
  "errors": [],
  "orderId": "CHECK_QUALITY__1759316235997"
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H76530_state__000130.json
{
  "headerId": 45,
  "serialNumber": "SVR4H76530",
  "paused": false,
  "actionState": {
    "id": "CHECK_QUALITY__1759316235998",
    "timestamp": "2025-10-01T10:57:16.021420Z",
    "command": "CHECK_QUALITY",
    "state": "WAITING"
  },
  "timestamp": "2025-10-01T10:57:16.021873Z",
  "batteryState": {},
  "orderUpdateId": 7,
  "errors": [],
  "orderId": "CHECK_QUALITY__1759316235997"
}
