=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/module_v1_ff_NodeRed_serial_order.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "timestamp": {
      "type": "string"
    },
    "orderId": {
      "type": "string"
    },
    "orderUpdateId": {
      "type": "integer"
    },
    "action": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "command": {
          "type": "string"
        },
        "metadata": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "workpieceId": {
              "type": "string"
            },
            "workpiece": {
              "type": "object",
              "properties": {
                "workpieceId": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                },
                "history": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "ts": {
                        "type": "integer"
                      },
                      "code": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "code",
                      "ts"
                    ]
                  }
                },
                "state": {
                  "type": "string"
                }
              },
              "required": [
                "history",
                "state",
                "type",
                "workpieceId"
              ]
            }
          }
        }
      },
      "required": [
        "command",
        "id",
        "metadata"
      ]
    },
    "serialNumber": {
      "type": "string"
    }
  },
  "required": [
    "action",
    "orderId",
    "orderUpdateId",
    "timestamp"
  ],
  "title": "Module_V1_Ff_Nodered_Serial_Order Schema",
  "description": "Granular schema for module_v1_ff_NodeRed_serial_order topics from 47 examples",
  "category": "module",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_SVR4H76530_order__000370.json
{
  "timestamp": "2025-10-01T09:40:23.104Z",
  "serialNumber": "SVR4H76530",
  "orderId": "d41940cc-356f-4c98-8352-d57c039b9b8e",
  "orderUpdateId": 7,
  "action": {
    "id": "71d1a4a5-b745-4bb1-a912-5ec45d1da862",
    "command": "PICK",
    "metadata": {
      "type": "WHITE",
      "workpieceId": "047b8bca341291"
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_SVR3QA2098_order__000172.json
{
  "timestamp": "2025-10-01T11:19:38.229Z",
  "serialNumber": "SVR3QA2098",
  "orderId": "aa74c367-dfc6-4c3b-b669-af293ea717f1",
  "orderUpdateId": 5,
  "action": {
    "id": "1d6b6de5-68e5-4387-914c-9d6ffe4f29ca",
    "command": "DROP",
    "metadata": {
      "type": "RED",
      "workpieceId": "040a8dca341291"
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_SVR3QA0022_order__000142.json
{
  "timestamp": "2025-10-01T11:35:10.201Z",
  "serialNumber": "SVR3QA0022",
  "orderId": "a2d2309a-6395-4f83-90de-b9edd85c5f02",
  "orderUpdateId": 3,
  "action": {
    "id": "87df2fe0-b887-414b-b17b-2a2691021a3a",
    "command": "PICK",
    "metadata": {
      "type": "RED",
      "workpieceId": "040a8dca341291"
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H76530_order__000405.json
{
  "serialNumber": "SVR4H76530",
  "orderId": "0f77cfd1-c4ec-4e5f-8262-d9de2add939a",
  "orderUpdateId": 10,
  "timestamp": "2025-10-01T10:14:18.407Z",
  "action": {
    "command": "CHECK_QUALITY",
    "id": "205375e9-ecb6-43b6-a65d-e8a4d9f8df74",
    "metadata": {
      "type": "RED",
      "workpieceId": "04fa8cca341290"
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_NodeRed_SVR4H76530_order__000466.json
{
  "serialNumber": "SVR4H76530",
  "orderId": "65b5edec-e634-4485-86c9-af4b8ad4d3f4",
  "orderUpdateId": 10,
  "timestamp": "2025-10-01T10:16:30.280Z",
  "action": {
    "command": "CHECK_QUALITY",
    "id": "a8d53f9a-aaf2-4a6c-a2f1-f81ee61c8491",
    "metadata": {
      "type": "RED",
      "workpieceId": "04808dca341291"
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_SVR4H73275_order__000244.json
{
  "timestamp": "2025-10-01T10:06:22.431Z",
  "serialNumber": "SVR4H73275",
  "orderId": "8b54cc26-e37b-4428-887e-35da7fb574fd",
  "orderUpdateId": 1,
  "action": {
    "id": "789b7014-836d-44d2-b17b-2d661222c96b",
    "command": "DROP",
    "metadata": {
      "workpiece": {
        "workpieceId": "047389ca341291",
        "type": "BLUE",
        "history": [],
        "state": "PROCESSED"
      }
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_SVR3QA2098_order__000373.json
{
  "timestamp": "2025-10-01T10:13:25.637Z",
  "serialNumber": "SVR3QA2098",
  "orderId": "0f77cfd1-c4ec-4e5f-8262-d9de2add939a",
  "orderUpdateId": 3,
  "action": {
    "id": "58aefacb-3bf6-4fa1-828d-11bd5a2efbfe",
    "command": "PICK",
    "metadata": {
      "type": "RED",
      "workpieceId": "04fa8cca341290"
    }
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/tests/test_payloads_for_topic/module_v1_ff_SVR3QA0022_order__000094.json
{
  "timestamp": "2025-10-01T11:33:13.516Z",
  "serialNumber": "SVR3QA0022",
  "orderId": "e35d0f89-8cc5-4672-84bf-d408b31ea121",
  "orderUpdateId": 3,
  "action": {
    "id": "5fedde2e-2524-4fa5-ad30-6d3183bbb126",
    "command": "PICK",
    "metadata": {
      "type": "RED",
      "workpieceId": "04f08dca341290"
    }
  }
}
