=== OliverBerger-ORBIS/ORBIS-Modellfabrik/omf2/registry/schemas/module_v1_ff_NodeRed_serial_factsheet.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "headerId": {
      "type": "integer"
    },
    "localizationParameters": {
      "type": "object"
    },
    "protocolLimits": {
      "type": "object"
    },
    "protocolFeatures": {
      "type": "object",
      "properties": {
        "moduleParameters": {
          "type": "object",
          "properties": {
            "clearModuleOnPick": {
              "type": "boolean"
            }
          },
          "required": [
            "clearModuleOnPick"
          ]
        },
        "moduleActions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "actionParameters": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "parameterDescription": {
                      "type": "string"
                    },
                    "parameterName": {
                      "type": "string"
                    },
                    "parameterType": {
                      "type": "string"
                    },
                    "isOptional": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "parameterDescription",
                    "parameterName",
                    "parameterType"
                  ]
                }
              },
              "actionType": {
                "type": "string"
              },
              "actionScopes": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "actionType"
            ]
          }
        }
      },
      "required": [
        "moduleActions"
      ]
    },
    "version": {
      "type": "string"
    },
    "serialNumber": {
      "type": "string"
    },
    "timestamp": {
      "type": "string"
    },
    "physicalParameters": {
      "type": "object"
    },
    "loadSpecification": {
      "type": "object",
      "properties": {
        "loadSets": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "loadType": {
                "type": "string"
              },
              "setName": {
                "type": "string"
              }
            },
            "required": [
              "loadType",
              "setName"
            ]
          }
        }
      },
      "required": [
        "loadSets"
      ]
    },
    "typeSpecification": {
      "type": "object",
      "properties": {
        "moduleClass": {
          "type": "string"
        },
        "seriesName": {
          "type": "string"
        }
      },
      "required": [
        "moduleClass",
        "seriesName"
      ]
    },
    "manufacturer": {
      "type": "string"
    }
  },
  "required": [
    "headerId",
    "loadSpecification",
    "localizationParameters",
    "manufacturer",
    "physicalParameters",
    "protocolFeatures",
    "protocolLimits",
    "serialNumber",
    "timestamp",
    "typeSpecification",
    "version"
  ],
  "title": "Module_V1_Ff_Nodered_Serial_Factsheet Schema",
  "description": "Granular schema for module_v1_ff_NodeRed_serial_factsheet topics from 14 examples",
  "category": "module",
  "additionalProperties": true
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/integrations/APS-CCU/nodeRed/factsheets/factsheet-aiqs.json
{
  "headerId": 1,
  "timestamp": "<replace_in_vda5050>",
  "version": "0.1.1+git9005fdf",
  "manufacturer": "Fischertechnik",
  "serialNumber": "<replace_in_vda5050>",
  "typeSpecification": {
    "seriesName": "MOD-FF22+AIQS+24V",
    "moduleClass": "AIQS"
  },
  "physicalParameters": {},
  "protocolLimits": {},
  "protocolFeatures": {
    "moduleActions": [
      {
        "actionType": "PICK",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece to pick up and process"
          }
        ]
      },
      {
        "actionType": "DROP",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece that should be put on the FTS",
            "isOptional": true
          }
        ]
      },
      {
        "actionType": "CHECK_QUALITY",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece that should checked",
            "isOptional": true
          }
        ]
      },
      {
        "actionType": "startCalibration",
        "actionScopes": [
          "INSTANT"
        ]
      },
      {
        "actionType": "stopCalibration",
        "actionScopes": [
          "INSTANT"
        ]
      },
      {
        "actionType": "setCalibrationValues",
        "actionScopes": [
          "INSTANT"
        ],
        "actionParameters": [
          {
            "parameterName": "references",
            "parameterType": "array",
            "parameterDescription": "Array of ReferenceValues objects with referenceKey and referenceValue"
          }
        ]
      },
      {
        "actionType": "storeCalibrationValues",
        "actionScopes": [
          "INSTANT"
        ],
        "actionParameters": [
          {
            "parameterName": "references",
            "parameterType": "array",
            "parameterDescription": "Array of ReferenceValues objects with referenceKey and referenceValue",
            "isOptional": true
          }
        ]
      },
      {
        "actionType": "selectCalibrationPosition",
        "actionScopes": [
          "INSTANT"
        ],
        "actionParameters": [
          {
            "parameterName": "position",
            "parameterType": "string",
            "parameterDescription": "Position to select"
          }
        ]
      },
      {
        "actionType": "testCalibrationPosition",
        "actionScopes": [
          "INSTANT"
        ],
        "actionParameters": [
          {
            "parameterName": "position",
            "parameterType": "string",
            "parameterDescription": "Position to test"
          }
        ]
      },
      {
        "actionType": "resetCalibration",
        "actionScopes": [
          "INSTANT"
        ],
        "actionParameters": [
          {
            "parameterName": "factory",
            "parameterType": "boolean",
            "parameterDescription": "Reset to factory defaults",
            "isOptional": true
          }
        ]
      }
    ]
  },
  "localizationParameters": {},
  "loadSpecification": {
    "loadSets": [
      {
        "setName": "WHITES",
        "loadType": "WHITE"
      },
      {
        "setName": "REDS",
        "loadType": "RED"
      },
      {
        "setName": "BLUES",
        "loadType": "BLUE"
      }
    ]
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/integrations/APS-CCU/nodeRed/factsheets/factsheet-drill.json
{
  "headerId": 1,
  "timestamp": "<replace_in_vda5050>",
  "version": "0.1.1+git4f766a7",
  "manufacturer": "Fischertechnik",
  "serialNumber": "<replace_in_vda5050>",
  "typeSpecification": {
    "seriesName": "MOD-FF22+DRILL+24V",
    "moduleClass": "DRILL"
  },
  "physicalParameters": {},
  "protocolLimits": {},
  "protocolFeatures": {
    "moduleActions": [
      {
        "actionType": "DROP",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece that should be put on the FTS",
            "isOptional": true
          }
        ]
      },
      {
        "actionType": "PICK",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece to pick up and process"
          }
        ]
      },
      {
        "actionType": "DRILL",
        "actionParameters": [
          {
            "parameterName": "duration",
            "parameterType": "number",
            "parameterDescription": "Set the duration of the drilling operation"
          },
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece to process",
            "isOptional": true
          }
        ]
      }
    ]
  },
  "localizationParameters": {},
  "loadSpecification": {
    "loadSets": [
      {
        "setName": "WHITES",
        "loadType": "WHITE"
      },
      {
        "setName": "REDS",
        "loadType": "RED"
      },
      {
        "setName": "BLUES",
        "loadType": "BLUE"
      }
    ]
  }
}

=== OliverBerger-ORBIS/ORBIS-Modellfabrik/tests/test_omf2/test_payloads_for_topic/module_v1_ff_SVR3QA2098_factsheet__000178.json
{
  "headerId": 1,
  "timestamp": "2025-10-01T11:04:25.992Z",
  "version": "1.3.0",
  "manufacturer": "Fischertechnik",
  "serialNumber": "SVR3QA2098",
  "typeSpecification": {
    "seriesName": "MOD-FF22+MILL+24V",
    "moduleClass": "MILL"
  },
  "physicalParameters": {},
  "protocolLimits": {},
  "protocolFeatures": {
    "moduleActions": [
      {
        "actionType": "DROP",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece that should be put on the FTS",
            "isOptional": true
          }
        ]
      },
      {
        "actionType": "PICK",
        "actionParameters": [
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece to pick up and process"
          }
        ]
      },
      {
        "actionType": "MILL",
        "actionParameters": [
          {
            "parameterName": "duration",
            "parameterType": "number",
            "parameterDescription": "Set the duration of the milling operation"
          },
          {
            "parameterName": "type",
            "parameterType": "string",
            "parameterDescription": "Type of workpiece to process",
            "isOptional": true
          }
        ]
      }
    ]
  },
  "localizationParameters": {},
  "loadSpecification": {
    "loadSets": [
      {
        "setName": "WHITES",
        "loadType": "WHITE"
      },
      {
        "setName": "REDS",
        "loadType": "RED"
      },
      {
        "setName": "BLUES",
        "loadType": "BLUE"
      }
    ]
  }
}
